server:
  port: 80
logging:
  level:
    root: WARN
    com.jcj.miniweb: ERROR
  file: logs/system.log
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://115.37.89.22:3306/miniweb?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root



