spring:
  profiles:
    active: dev #默认启用的配置文件，不用写配置文件的全称，写短线后的名称就行了
  jpa:
    hibernate:
      #注意：数据库要预先建立好，因为hibernate只会建表，不会建库
      #update：表示自动根据model对象来更新表结构，启动hibernate时会自动检查数据库，如果缺少表，则自动建表；如果表里缺少列，则自动添加列。
      #create：启动hibernate时，自动删除原来的表，新建所有的表，所以每次启动后的以前数据都会丢失。
      #create-drop：启动hibernate时，自动创建表，程序关闭时，自动把相应的表都删除。所以程序结束时，表和数据也不会再存在。
      ddl-auto: update
    show-sql: true #是否输出SQL语句




